FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y git python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/undergroundchurch/bible-api.git .
RUN git checkout dev

RUN npm ci && npm rebuild
RUN node CreateUsers.js

EXPOSE 3001

CMD ["npm", "start"]
